# Generated by Django 3.1.6 on 2021-02-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='image1', upload_to='images'),
            preserve_default=False,
        ),
    ]
